# Generated by Django 5.2 on 2025-06-23 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_users_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_staff',
        ),
    ]
