# Generated by Django 5.2.1 on 2025-05-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_rooms_description_rooms_name_rooms_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название комнаты'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена за ночь'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество номеров'),
        ),
    ]
