# Generated by Django 5.2.1 on 2025-05-24 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_rooms_description_alter_rooms_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rooms',
            options={'verbose_name': 'Номер', 'verbose_name_plural': 'Номера'},
        ),
    ]
