# Generated by Django 5.2.1 on 2025-05-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Дата начала')),
                ('date_to', models.DateField(verbose_name='Дата окончания')),
                ('price_per_day', models.PositiveIntegerField(verbose_name='Цена за день')),
                ('total_days', models.PositiveIntegerField(editable=False, verbose_name='Всего дней')),
                ('total_price', models.PositiveIntegerField(editable=False, verbose_name='Итоговая цена бронирования')),
            ],
        ),
    ]
