# Generated by Django 5.2.1 on 2025-05-24 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('rooms', '0003_alter_rooms_description_alter_rooms_name_and_more'),
        ('users', '0003_alter_users_email_alter_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='rooms',
            field=models.ManyToManyField(to='rooms.rooms', verbose_name='Номера'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookings',
            name='price_per_day',
            field=models.PositiveIntegerField(editable=False, verbose_name='Цена за день'),
        ),
    ]
