# Generated by Django 5.2.1 on 2025-05-24 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_bookings_rooms_bookings_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
    ]
