# Generated by Django 5.2 on 2025-06-23 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_bookings_options'),
        ('users', '0005_users_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='price_per_day',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Цена за день'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='total_days',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Всего дней'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='total_price',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Итоговая цена бронирования'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.users', verbose_name='Пользователь'),
        ),
    ]
